checks:
    ruby: true
build:
    environment:
        node: '5.1.0'
    tests:
        before:
            - gem install rubocop
        override: 
            - 
                command: 'rubocop --format json -o rubocop-data'
                analysis:
                    file: 'rubocop-data'
                    format: 'rubocop-json'
